[project]
name = "github-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "NitinDabar", email = "nitindabar12@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "uvicorn>=0.54.0",
]

[project.scripts]
github-rag = "github_rag:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
